{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2025-32910"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in libsoup, where soup_auth_digest_authenticate() is vulnerable to a NULL pointer dereference. This issue may cause the libsoup client to crash."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://access.redhat.com/security/cve/CVE-2025-32910",
          "refsource": "",
          "tags": [],
          "url": "https://access.redhat.com/security/cve/CVE-2025-32910"
        },
        {
          "name": "RHBZ#2359354",
          "refsource": "",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2359354"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-04-15T18:39Z",
  "publishedDate": "2025-04-14T15:15Z"
}