{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:linuxfoundation:pytorch:2.6.0:-:*:*:*:python:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cna@vuldb.com",
      "ID": "CVE-2025-3730"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A vulnerability, which was classified as problematic, was found in PyTorch 2.6.0. Affected is the function torch.nn.functional.ctc_loss of the file aten/src/ATen/native/LossCTC.cpp. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used. The real existence of this vulnerability is still doubted at the moment. The name of the patch is 46fc5d8e360127361211cb237d5f9eef0223e567. It is recommended to apply a patch to fix this issue. The security policy of the project warns to use unknown models which might establish malicious effects."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/pytorch/pytorch/issues/150835",
          "refsource": "",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/pytorch/pytorch/issues/150835"
        },
        {
          "name": "https://github.com/pytorch/pytorch/issues/150835",
          "refsource": "",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/pytorch/pytorch/issues/150835"
        },
        {
          "name": "https://github.com/pytorch/pytorch/issues/150835#issue-2979082232",
          "refsource": "",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/pytorch/pytorch/issues/150835#issue-2979082232"
        },
        {
          "name": "https://github.com/pytorch/pytorch/pull/150981",
          "refsource": "",
          "tags": [
            "Issue Tracking",
            "Patch"
          ],
          "url": "https://github.com/pytorch/pytorch/pull/150981"
        },
        {
          "name": "https://github.com/timocafe/tewart-pytorch/commit/46fc5d8e360127361211cb237d5f9eef0223e567",
          "refsource": "",
          "tags": [
            "Patch"
          ],
          "url": "https://github.com/timocafe/tewart-pytorch/commit/46fc5d8e360127361211cb237d5f9eef0223e567"
        },
        {
          "name": "VDB-305076 | CTI Indicators (IOB, IOC, IOA)",
          "refsource": "",
          "tags": [
            "Permissions Required",
            "VDB Entry"
          ],
          "url": "https://vuldb.com/?ctiid.305076"
        },
        {
          "name": "VDB-305076 | PyTorch LossCTC.cpp torch.nn.functional.ctc_loss denial of service",
          "refsource": "",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ],
          "url": "https://vuldb.com/?id.305076"
        },
        {
          "name": "Submit #553645 | pytorch pytorch (in torch.nn.functional.ctc_loss) 2.6.0 Denial of Service",
          "refsource": "",
          "tags": [
            "Third Party Advisory",
            "VDB Entry",
            "Exploit"
          ],
          "url": "https://vuldb.com/?submit.553645"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "LOCAL",
        "availabilityImpact": "HIGH",
        "baseScore": 5.5,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
        "version": "3.1"
      },
      "exploitabilityScore": 1.8,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2025-05-28T17:35Z",
  "publishedDate": "2025-04-16T21:15Z"
}