{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2024-9774"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A vulnerability was found in python-sql where unary operators do not escape non-Expression."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "RHBZ#2332734",
          "refsource": "",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2332734"
        },
        {
          "name": "https://discuss.tryton.org/t/security-release-for-issue-93/7889/3",
          "refsource": "",
          "tags": [],
          "url": "https://discuss.tryton.org/t/security-release-for-issue-93/7889/3"
        },
        {
          "name": "https://lists.debian.org/debian-lts-announce/2024/10/msg00023.html",
          "refsource": "",
          "tags": [],
          "url": "https://lists.debian.org/debian-lts-announce/2024/10/msg00023.html"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-01-06T21:15Z",
  "publishedDate": "2024-12-27T02:15Z"
}