{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:lightningai:pytorch_lightning:2.3.2:*:*:*:*:python:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "security@huntr.dev",
      "ID": "CVE-2024-8020"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A vulnerability in lightning-ai/pytorch-lightning version 2.3.2 allows an attacker to cause a denial of service by sending an unexpected POST request to the `/api/v1/state` endpoint of `LightningApp`. This issue occurs due to improper handling of unexpected state values, which results in the server shutting down."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-400"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://huntr.com/bounties/8b642a78-2b80-4fb0-9b2f-8ba0ff37db6a",
          "refsource": "",
          "tags": [
            "Exploit",
            "Third Party Advisory"
          ],
          "url": "https://huntr.com/bounties/8b642a78-2b80-4fb0-9b2f-8ba0ff37db6a"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-08-01T01:43Z",
  "publishedDate": "2025-03-20T10:15Z"
}