{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:portainer:portainer:*:*:*:*:*:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "2.20.2",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2024-33662"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Portainer before 2.20.2 improperly uses an encryption algorithm in the AesEncrypt function."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/portainer/portainer/compare/2.20.1...2.20.2",
          "refsource": "",
          "tags": [
            "Product"
          ],
          "url": "https://github.com/portainer/portainer/compare/2.20.1...2.20.2"
        },
        {
          "name": "https://github.com/portainer/portainer/issues/11737",
          "refsource": "",
          "tags": [
            "Issue Tracking"
          ],
          "url": "https://github.com/portainer/portainer/issues/11737"
        },
        {
          "name": "https://www.portainer.io",
          "refsource": "",
          "tags": [
            "Product"
          ],
          "url": "https://www.portainer.io"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-05-21T18:07Z",
  "publishedDate": "2024-10-02T05:15Z"
}