{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.9.8",
            "versionStartIncluding": "17.1.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.10.6",
            "versionStartIncluding": "17.10.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.11.2",
            "versionStartIncluding": "17.11.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.9.8",
            "versionStartIncluding": "17.1.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.10.6",
            "versionStartIncluding": "17.10.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.11.2",
            "versionStartIncluding": "17.11.0",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@gitlab.com",
      "ID": "CVE-2024-8973"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue has been discovered in GitLab CE/EE affecting all versions starting from 17.1 prior to 17.9.8, from 17.10 prior to 17.10.6, and from 17.11 prior to 17.11.2. It was possible to cause a DoS condition via GitHub import requests using a malicious crafted payload."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-770"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "GitLab Issue #491041",
          "refsource": "",
          "tags": [
            "Broken Link"
          ],
          "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/491041"
        },
        {
          "name": "HackerOne Bug Bounty Report #2711684",
          "refsource": "",
          "tags": [
            "Permissions Required"
          ],
          "url": "https://hackerone.com/reports/2711684"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "HIGH",
        "baseScore": 7.5,
        "baseSeverity": "HIGH",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "version": "3.1"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2025-08-08T16:54Z",
  "publishedDate": "2025-05-09T17:15Z"
}