{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2023-43782"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Cadence through 0.9.2 2023-08-21 uses an Insecure /tmp/.cadence-aloop-daemon.x Temporary File. The file is used even if it has been created by a local adversary before Cadence started. The adversary can then delete the file, disrupting Cadence."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.suse.com/show_bug.cgi?id=1213983",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugzilla.suse.com/show_bug.cgi?id=1213983"
        },
        {
          "name": "https://github.com/falkTX/Cadence",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/falkTX/Cadence"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2023-09-22T13:24Z",
  "publishedDate": "2023-09-22T06:15Z"
}